# Generated by Django 3.1.4 on 2021-01-18 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poly',
            fields=[
                ('y_axis', models.TextField(blank=True, null=True)),
                ('parameter', models.TextField(blank=True, null=True)),
                ('mse', models.FloatField(blank=True, null=True)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('spectrum', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.spectrum')),
            ],
        ),
    ]
