# Generated by Django 3.1.4 on 2021-01-21 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spectraModelling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('y_axis', models.TextField()),
                ('x_range_max', models.FloatField(blank=True, null=True)),
                ('x_range_min', models.FloatField(blank=True, null=True)),
                ('parameter', models.TextField(blank=True, null=True)),
                ('mse', models.FloatField(blank=True, null=True)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('poly', models.ManyToManyField(to='spectraModelling.Poly')),
            ],
        ),
    ]
