# Generated by Django 3.1.4 on 2021-01-26 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spectraModelling', '0002_match'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'verbose_name_plural': 'Matches'},
        ),
        migrations.AddField(
            model_name='poly',
            name='similar_pk',
            field=models.ManyToManyField(to='spectraModelling.Poly'),
        ),
    ]
