# Generated by Django 3.1.4 on 2021-05-11 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spectraModelling', '0003_auto_20210126_2147'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'verbose_name_plural': 'Match history'},
        ),
    ]
