# Generated by Django 3.1.4 on 2020-12-09 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NirProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('nir_type', models.CharField(choices=[('N', 'Not mentioned'), ('U', 'Unknown'), ('A', 'Type A'), ('B', 'Type B')], default='N', max_length=1)),
                ('nir_method', models.TextField(blank=True, null=True)),
                ('nir_configuration', models.TextField(blank=True, null=True)),
                ('figure_id', models.CharField(max_length=10)),
                ('figure_title', models.CharField(max_length=100)),
                ('figure_caption', models.CharField(max_length=300)),
                ('x_label', models.CharField(max_length=30)),
                ('y_label', models.CharField(max_length=30)),
                ('x_min', models.FloatField()),
                ('x_max', models.FloatField()),
                ('y_min', models.FloatField()),
                ('y_max', models.FloatField()),
                ('reference_type', models.CharField(choices=[('A', 'Allied Scientific Pro'), ('L', 'Literature'), ('O', 'Other')], default='A', max_length=1)),
                ('reference_title', models.CharField(max_length=100)),
                ('reference_link', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Spectrum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=60)),
                ('code', models.CharField(max_length=60)),
                ('color', models.CharField(max_length=60)),
                ('y_axis', models.TextField()),
                ('x_range_max', models.FloatField(blank=True, null=True)),
                ('x_range_min', models.FloatField(blank=True, null=True)),
                ('nir_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.nirprofile')),
            ],
            options={
                'verbose_name_plural': 'Spectra',
            },
        ),
    ]
