# Generated by Django 3.1.4 on 2021-03-08 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spectrum',
            name='spec_pic',
            field=models.ImageField(blank=True, null=True, upload_to='spec_pics/', verbose_name='Upload pic'),
        ),
    ]
