# Generated by Django 3.1.4 on 2021-03-01 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_spectrum_spec_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='spectrum',
            name='pic_name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
