# Generated by Django 3.1.4 on 2021-03-02 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_spectrum_pic_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spectrum',
            name='pic_name',
        ),
        migrations.AlterField(
            model_name='spectrum',
            name='spec_pic',
            field=models.ImageField(blank=True, null=True, upload_to='spec_pics/%Y/%m', verbose_name='Upload_pic'),
        ),
    ]
