# Generated by Django 3.1.4 on 2021-03-03 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210302_1316'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpectraDisplay',
            fields=[
            ],
            options={
                'verbose_name': 'Spectrum information',
                'verbose_name_plural': 'Spectra information',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.spectrum',),
        ),
        migrations.AlterField(
            model_name='spectrum',
            name='spec_pic',
            field=models.ImageField(blank=True, null=True, upload_to='spec_pics/%Y/%m', verbose_name='Upload pic'),
        ),
    ]
