# Generated by Django 3.1.4 on 2021-07-10 22:01

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210710_0541'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='owner',
            managers=[
                ('o', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='nirprofile',
            name='owner',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.owner'),
        ),
        migrations.AlterField(
            model_name='spectrum',
            name='owner',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.owner'),
        ),
    ]
