# Generated by Django 3.1.4 on 2021-03-03 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210303_1315'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SpectraDisplay',
        ),
    ]
