# Generated by Django 3.1.4 on 2021-03-15 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210312_2031'),
        ('core', '0011_auto_20210312_0854'),
    ]

    operations = [
    ]
