# Generated by Django 3.1.4 on 2021-03-15 20:52

import core.models
from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20210315_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spectrum',
            name='spec_pic',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='JPEG', keep_meta=True, null=True, quality=75, size=[600, 400], storage=core.models.myStorage(), upload_to='nirpics', verbose_name='Upload pic'),
        ),
    ]
