# Generated by Django 3.1.4 on 2021-03-17 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210315_1803'),
        ('core', '0014_auto_20210315_1652'),
    ]

    operations = [
    ]
