# Generated by Django 3.1.4 on 2021-02-05 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('predictionModel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.TextField(blank=True, default=2, null=True)),
                ('calibration', models.ManyToManyField(to='core.Spectrum')),
            ],
        ),
    ]
