# Generated by Django 3.1.4 on 2021-02-08 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictionModel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcamodel',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pcamodel',
            name='order',
            field=models.IntegerField(default=2),
        ),
    ]
