# Generated by Django 3.1.4 on 2021-02-09 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictionModel', '0002_auto_20210208_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcamodel',
            name='transform',
            field=models.TextField(blank=True, null=True),
        ),
    ]
