# Generated by Django 3.1.4 on 2021-02-23 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('predictionModel', '0003_pcamodel_transform'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=2)),
                ('score', models.FloatField(blank=True, null=True)),
                ('mse', models.FloatField(blank=True, null=True)),
                ('x_rotations', models.TextField(blank=True, null=True)),
                ('x_std', models.TextField(blank=True, null=True)),
                ('x_mean', models.TextField(blank=True, null=True)),
                ('y_mean', models.TextField(blank=True, null=True)),
                ('coef', models.TextField(blank=True, null=True)),
                ('transform', models.TextField(blank=True, null=True)),
                ('calibration', models.ManyToManyField(to='core.Spectrum')),
            ],
        ),
    ]
