# Generated by Django 3.1.4 on 2021-02-10 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predictionModel', '0003_pcamodel_transform'),
        ('predictionModel', '0002_plsmodel'),
    ]

    operations = [
    ]
