# Generated by Django 3.1.4 on 2021-02-26 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictionModel', '0004_plsmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='plsmodel',
            name='y_pred',
            field=models.TextField(blank=True, null=True),
        ),
    ]
