# Generated by Django 3.1.4 on 2021-02-11 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictionModel', '0004_merge_20210210_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='plsmodel',
            name='order',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='plsmodel',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plsmodel',
            name='transform',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plsmodel',
            name='component',
            field=models.TextField(blank=True, null=True),
        ),
    ]
