# Generated by Django 3.1.4 on 2021-02-11 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predictionModel', '0005_auto_20210211_0900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plsmodel',
            name='component',
        ),
    ]
