# Generated by Django 3.1.4 on 2021-04-05 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictionModel', '0005_plsmodel_y_pred'),
    ]

    operations = [
        migrations.AddField(
            model_name='plsmodel',
            name='preprocessed',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
