# Generated by Django 3.1.4 on 2021-05-11 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictionModel', '0006_plsmodel_preprocessed'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcamodel',
            name='meta',
            field=models.TextField(blank=True, null=True),
        ),
    ]
