# Generated by Django 3.1.4 on 2021-02-17 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictionModel', '0007_plsmodel_mse'),
    ]

    operations = [
        migrations.AddField(
            model_name='plsmodel',
            name='x_rotations',
            field=models.TextField(blank=True, null=True),
        ),
    ]
