# Generated by Django 3.1.4 on 2021-02-17 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictionModel', '0008_plsmodel_x_rotations'),
    ]

    operations = [
        migrations.AddField(
            model_name='plsmodel',
            name='x_mean',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plsmodel',
            name='x_std',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plsmodel',
            name='y_mean',
            field=models.TextField(blank=True, null=True),
        ),
    ]
