# Generated by Django 3.1.4 on 2021-02-18 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predictionModel', '0010_plsmodel_coef'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plsmodel',
            name='x_mean',
        ),
        migrations.RemoveField(
            model_name='plsmodel',
            name='x_std',
        ),
    ]
