# Generated by Django 3.1.4 on 2021-02-19 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictionModel', '0011_auto_20210218_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='plsmodel',
            name='x_mean',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plsmodel',
            name='x_std',
            field=models.TextField(blank=True, null=True),
        ),
    ]
