# Generated by Django 3.1.4 on 2021-02-23 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictionModel', '0012_auto_20210219_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='plsmodel',
            name='y_pred',
            field=models.TextField(blank=True, null=True),
        ),
    ]
