# Generated by Django 3.1.4 on 2021-02-26 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictionModel', '0014_remove_plsmodel_y_pred'),
    ]

    operations = [
        migrations.AddField(
            model_name='plsmodel',
            name='y_pred',
            field=models.TextField(blank=True, null=True),
        ),
    ]
