# Generated by Django 3.1.4 on 2021-03-15 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predictionModel', '0015_plsmodel_y_pred'),
        ('predictionModel', '0005_plsmodel_y_pred'),
    ]

    operations = [
    ]
