# Generated by Django 3.1.4 on 2021-03-17 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predictionModel', '0016_merge_20210315_0934'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plsmodel',
            old_name='coef',
            new_name='x_train',
        ),
        migrations.RenameField(
            model_name='plsmodel',
            old_name='x_mean',
            new_name='y_train',
        ),
        migrations.RemoveField(
            model_name='plsmodel',
            name='x_rotations',
        ),
        migrations.RemoveField(
            model_name='plsmodel',
            name='x_std',
        ),
        migrations.RemoveField(
            model_name='plsmodel',
            name='y_mean',
        ),
    ]
