# Generated by Django 3.1.4 on 2021-03-23 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictionModel', '0017_auto_20210317_1428'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plsmodel',
            old_name='x_train',
            new_name='coef',
        ),
        migrations.RenameField(
            model_name='plsmodel',
            old_name='y_train',
            new_name='x_mean',
        ),
        migrations.AddField(
            model_name='plsmodel',
            name='x_rotations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plsmodel',
            name='x_std',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plsmodel',
            name='y_mean',
            field=models.TextField(blank=True, null=True),
        ),
    ]
