# Generated by Django 3.1.4 on 2021-04-26 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('component', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Ingredients Model',
                'verbose_name_plural': 'Ingredients Models',
            },
        ),
        migrations.CreateModel(
            name='StaticModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('component', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Static Model',
                'verbose_name_plural': 'Static Models',
            },
        ),
    ]
