# Generated by Django 3.1.4 on 2021-05-01 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterModelling', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredientsmodel',
            old_name='component',
            new_name='validation',
        ),
        migrations.RenameField(
            model_name='staticmodel',
            old_name='component',
            new_name='applied_model',
        ),
        migrations.RenameField(
            model_name='staticmodel',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='ingredientsmodel',
            name='name',
        ),
        migrations.AddField(
            model_name='ingredientsmodel',
            name='applied_model',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ingredientsmodel',
            name='count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ingredientsmodel',
            name='n_comp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ingredientsmodel',
            name='origin',
            field=models.CharField(default='', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingredientsmodel',
            name='predected_values',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ingredientsmodel',
            name='preprocessed',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ingredientsmodel',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ingredientsmodel',
            name='title',
            field=models.CharField(default='', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingredientsmodel',
            name='true_values',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staticmodel',
            name='count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staticmodel',
            name='n_comp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staticmodel',
            name='preprocessed',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staticmodel',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
