# Generated by Django 3.1.4 on 2021-05-01 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterModelling', '0002_auto_20210501_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientsmodel',
            name='trans',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staticmodel',
            name='trans',
            field=models.TextField(blank=True, null=True),
        ),
    ]
