# Generated by Django 3.1.4 on 2021-05-01 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterModelling', '0003_auto_20210501_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticmodel',
            name='profile',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staticmodel',
            name='titles',
            field=models.TextField(blank=True, null=True),
        ),
    ]
