# Generated by Django 3.1.4 on 2021-05-01 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterModelling', '0004_auto_20210501_0943'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staticmodel',
            old_name='titles',
            new_name='spectra',
        ),
    ]
