# Generated by Django 3.1.4 on 2021-04-05 19:34

from django.db import migrations, models
import preprocessingFilters.models


class Migration(migrations.Migration):

    dependencies = [
        ('preprocessingFilters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sgfilter',
            name='mode',
            field=models.CharField(choices=[('M', 'Mirror'), ('C', 'Constant'), ('N', 'Nearest'), ('W', 'wrap'), ('I', 'Interp')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='sgfilter',
            name='window_length',
            field=models.IntegerField(default=13, validators=[preprocessingFilters.models.validate_window]),
        ),
    ]
